import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { prisma } from '@aop/db';
import { NotFoundError, ValidationError } from '@aop/utils';
import { uploadToS3 } from '../../lib/s3.js';
import type { GenerateDocDto } from './documents.schemas.js';

// ---------------------------------------------------------------------------
// Minimal PDF builder helpers
// ---------------------------------------------------------------------------

async function buildPdfBase(title: string): Promise<{
  pdfDoc: PDFDocument;
  page: ReturnType<PDFDocument['addPage']>;
  font: Awaited<ReturnType<PDFDocument['embedFont']>>;
  boldFont: Awaited<ReturnType<PDFDocument['embedFont']>>;
  y: () => number;
  nextLine: (lines?: number) => void;
}> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let yPos = 800;

  // Header
  page.drawText('AURUM OPERATIONS PLATFORM', {
    x: 50,
    y: yPos,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });
  yPos -= 20;
  page.drawText(title, {
    x: 50,
    y: yPos,
    size: 16,
    font: boldFont,
    color: rgb(0.1, 0.1, 0.1),
  });
  yPos -= 10;
  page.drawLine({
    start: { x: 50, y: yPos },
    end: { x: 545, y: yPos },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  yPos -= 20;

  return {
    pdfDoc,
    page,
    font,
    boldFont,
    y: () => yPos,
    nextLine: (lines = 1) => {
      yPos -= lines * 14;
    },
  };
}

function drawField(
  page: ReturnType<PDFDocument['addPage']>,
  label: string,
  value: string,
  x: number,
  y: number,
  font: Awaited<ReturnType<PDFDocument['embedFont']>>,
  boldFont: Awaited<ReturnType<PDFDocument['embedFont']>>,
): void {
  page.drawText(`${label}:`, { x, y, size: 9, font: boldFont, color: rgb(0.3, 0.3, 0.3) });
  page.drawText(value, { x: x + 160, y, size: 9, font, color: rgb(0.1, 0.1, 0.1) });
}

// ---------------------------------------------------------------------------
// Generator functions
// ---------------------------------------------------------------------------

async function generateCommercialInvoice(transactionId: string): Promise<Buffer> {
  const tx = await prisma.transaction.findUnique({
    where: { id: transactionId },
    include: {
      client: { select: { fullName: true, countryCode: true, entityType: true } },
      agent: { select: { companyName: true } },
      costItems: true,
    },
  });
  if (!tx) throw new NotFoundError('Transaction not found');

  const { pdfDoc, page, font, boldFont, y, nextLine } = await buildPdfBase('COMMERCIAL INVOICE');

  drawField(page, 'Invoice No', `INV-${transactionId}`, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Date', new Date().toISOString().split('T')[0], 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Transaction ID', transactionId, 50, y(), font, boldFont);
  nextLine(2);
  drawField(page, 'Seller', tx.agent.companyName, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Buyer / Client', tx.client.fullName, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Country', tx.client.countryCode, 50, y(), font, boldFont);
  nextLine(2);

  // Commodity
  page.drawText('COMMODITY DETAILS', { x: 50, y: y(), size: 10, font: boldFont });
  nextLine();
  drawField(page, 'Description', 'Gold (Au)', 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Gross Weight', `${tx.goldWeightGross.toString()} g`, 50, y(), font, boldFont);
  nextLine();
  drawField(
    page,
    'Fine Weight',
    tx.goldWeightFine ? `${tx.goldWeightFine.toString()} g` : 'TBC',
    50,
    y(),
    font,
    boldFont,
  );
  nextLine();
  drawField(
    page,
    'Purity',
    tx.assayPurity ? `${(Number(tx.assayPurity) * 100).toFixed(2)}%` : 'TBC',
    50,
    y(),
    font,
    boldFont,
  );
  nextLine();
  drawField(
    page,
    'LME Price (locked)',
    tx.lmePriceLocked ? `USD ${tx.lmePriceLocked.toString()}/troy oz` : 'TBC',
    50,
    y(),
    font,
    boldFont,
  );
  nextLine(2);

  const totalCosts = tx.costItems.reduce(
    (sum, c) => sum + Number(c.actualUsd ?? c.estimatedUsd ?? 0),
    0,
  );
  drawField(page, 'Total Costs (USD)', totalCosts.toFixed(2), 50, y(), font, boldFont);
  nextLine(3);

  page.drawText('Generated by AOP system — for operational purposes only', {
    x: 50,
    y: y(),
    size: 8,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  return Buffer.from(await pdfDoc.save());
}

async function generateAmlCocDeclaration(transactionId: string): Promise<Buffer> {
  const tx = await prisma.transaction.findUnique({
    where: { id: transactionId },
    include: {
      client: {
        select: {
          fullName: true,
          countryCode: true,
          kycStatus: true,
          sanctionsStatus: true,
          isPEP: true,
          isEDD: true,
        },
      },
    },
  });
  if (!tx) throw new NotFoundError('Transaction not found');

  const { pdfDoc, page, font, boldFont, y, nextLine } = await buildPdfBase('AML / COC DECLARATION');

  page.drawText('ANTI-MONEY LAUNDERING & CHAIN-OF-CUSTODY DECLARATION', {
    x: 50,
    y: y(),
    size: 10,
    font: boldFont,
  });
  nextLine(2);

  drawField(page, 'Transaction ID', transactionId, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Client', tx.client.fullName, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Country', tx.client.countryCode, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'KYC Status', tx.client.kycStatus, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Sanctions Status', tx.client.sanctionsStatus, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'PEP', tx.client.isPEP ? 'YES' : 'NO', 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'EDD Completed', tx.client.isEDD ? 'YES' : 'NO', 50, y(), font, boldFont);
  nextLine(2);

  const declaration = [
    'The undersigned hereby declares that:',
    '1. The gold subject to this transaction was lawfully mined and is',
    '   not the proceeds of any criminal activity.',
    '2. Full KYC/AML checks have been conducted on the client.',
    '3. No sanctions concerns have been identified.',
    '4. Chain of custody documentation is complete and on file.',
  ];

  for (const line of declaration) {
    page.drawText(line, { x: 50, y: y(), size: 9, font });
    nextLine();
  }

  nextLine(3);
  page.drawText('Compliance Officer Signature: ___________________________   Date: ____________', {
    x: 50,
    y: y(),
    size: 9,
    font,
  });
  nextLine(2);
  page.drawText('Generated by AOP system', {
    x: 50,
    y: y(),
    size: 8,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  return Buffer.from(await pdfDoc.save());
}

async function generateFinalSettlementStatement(transactionId: string): Promise<Buffer> {
  const tx = await prisma.transaction.findUnique({
    where: { id: transactionId },
    include: {
      client: { select: { fullName: true } },
      agent: { select: { companyName: true } },
      costItems: true,
      disbursements: { orderBy: { trancheNo: 'asc' } },
      settlement: true,
    },
  });
  if (!tx) throw new NotFoundError('Transaction not found');
  if (!tx.settlement) throw new ValidationError('Settlement record not yet created');

  const { pdfDoc, page, font, boldFont, y, nextLine } = await buildPdfBase(
    'FINAL SETTLEMENT STATEMENT',
  );

  drawField(page, 'Transaction ID', transactionId, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Client', tx.client.fullName, 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Agent', tx.agent.companyName, 50, y(), font, boldFont);
  nextLine();
  drawField(
    page,
    'Settlement Date',
    tx.settlement.approvedAt ? tx.settlement.approvedAt.toISOString().split('T')[0] : 'Pending',
    50,
    y(),
    font,
    boldFont,
  );
  nextLine(2);

  // Financials
  page.drawText('FINANCIAL SUMMARY', { x: 50, y: y(), size: 10, font: boldFont });
  nextLine();

  const grossProceeds =
    tx.lmePriceLocked && tx.goldWeightFine
      ? (Number(tx.lmePriceLocked) * Number(tx.goldWeightFine)) / 31.1035
      : 0;
  const totalCosts = tx.costItems.reduce(
    (sum, c) => sum + Number(c.actualUsd ?? c.estimatedUsd ?? 0),
    0,
  );
  const netAmount = grossProceeds - totalCosts;

  drawField(page, 'Gross Proceeds (USD)', grossProceeds.toFixed(2), 50, y(), font, boldFont);
  nextLine();
  drawField(page, 'Total Costs (USD)', totalCosts.toFixed(2), 50, y(), font, boldFont);
  nextLine();

  page.drawLine({
    start: { x: 50, y: y() - 4 },
    end: { x: 350, y: y() - 4 },
    thickness: 0.5,
    color: rgb(0.5, 0.5, 0.5),
  });
  nextLine();
  page.drawText(`Net Amount (USD): ${netAmount.toFixed(2)}`, {
    x: 50,
    y: y(),
    size: 11,
    font: boldFont,
  });
  nextLine(2);

  if (tx.disbursements.length > 0) {
    page.drawText('DISBURSEMENT TRANCHES', { x: 50, y: y(), size: 10, font: boldFont });
    nextLine();
    for (const d of tx.disbursements) {
      drawField(
        page,
        `Tranche ${d.trancheNo}`,
        `USD ${Number(d.amountUsd).toFixed(2)} — ${d.status}`,
        50,
        y(),
        font,
        boldFont,
      );
      nextLine();
    }
    nextLine();
  }

  drawField(page, 'Remittance Status', tx.settlement.remittanceStatus, 50, y(), font, boldFont);
  nextLine(3);
  page.drawText('Generated by AOP system', {
    x: 50,
    y: y(),
    size: 8,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });

  return Buffer.from(await pdfDoc.save());
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export async function generateSystemDocument(
  transactionId: string,
  dto: GenerateDocDto,
  generatedById: string,
): Promise<{ id: string; storageKey: string }> {
  let buffer: Buffer;
  let docTypeKey: 'COMMERCIAL_INVOICE' | 'AML_SCREENING_REPORT' | 'SETTLEMENT_STATEMENT';

  if (dto.documentType === 'COMMERCIAL_INVOICE') {
    buffer = await generateCommercialInvoice(transactionId);
    docTypeKey = 'COMMERCIAL_INVOICE';
  } else if (dto.documentType === 'AML_COC_DECLARATION') {
    buffer = await generateAmlCocDeclaration(transactionId);
    docTypeKey = 'AML_SCREENING_REPORT';
  } else {
    buffer = await generateFinalSettlementStatement(transactionId);
    docTypeKey = 'SETTLEMENT_STATEMENT';
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filename = `${dto.documentType}-${timestamp}.pdf`;
  const key = `documents/${transactionId}/${docTypeKey}/${filename}`;

  const { storageKey } = await uploadToS3(key, buffer, 'application/pdf');

  const retainUntil = new Date();
  retainUntil.setFullYear(retainUntil.getFullYear() + 10);

  // Supersede previous system-generated docs of same type
  await prisma.document.updateMany({
    where: {
      transactionId,
      documentType: docTypeKey,
      isSystemGenerated: true,
      approvalStatus: { not: 'SUPERSEDED' },
    },
    data: { approvalStatus: 'SUPERSEDED' },
  });

  const doc = await prisma.document.create({
    data: {
      transactionId,
      documentType: docTypeKey,
      filename,
      storageKey,
      mimeType: 'application/pdf',
      sizeBytes: buffer.length,
      uploadedBy: generatedById,
      isSystemGenerated: true,
      approvalStatus: 'APPROVED',
      approvedBy: generatedById,
      approvedAt: new Date(),
      retainUntil,
    },
  });

  return { id: doc.id, storageKey: doc.storageKey };
}
