import { Queue } from 'bullmq';
import type { Job } from 'bullmq';
import { prisma } from '@aop/db';
import { logger } from '@aop/utils';

// Monthly TAR cron: '0 3 1 * *'  (1st of each month, 06:00 EAT = 03:00 UTC)
export const MONTHLY_TAR_CRON = '0 3 1 * *';
// Weekly portfolio summary: Monday 07:00 EAT = 04:00 UTC
export const WEEKLY_PORTFOLIO_CRON = '0 4 * * 1';

export async function scheduleMonthlyTar(queue: Queue): Promise<void> {
  // Find a system user (first SUPER_ADMIN) to use as generatedBy
  // For the job itself, we just need the queue; actual user lookup happens in the processor
  await queue.add(
    'monthly-tar',
    { reportType: 'MONTHLY_TRANSACTION', autoGenerated: true },
    {
      repeat: { pattern: MONTHLY_TAR_CRON },
      removeOnComplete: 5,
      removeOnFail: 3,
    },
  );
}

export async function scheduleWeeklyPortfolio(queue: Queue): Promise<void> {
  await queue.add(
    'weekly-portfolio',
    { reportType: 'PORTFOLIO_SUMMARY', autoGenerated: true },
    {
      repeat: { pattern: WEEKLY_PORTFOLIO_CRON },
      removeOnComplete: 5,
      removeOnFail: 3,
    },
  );
}

export async function reportGenerationProcessor(
  job: Job<{ reportType: string; autoGenerated: boolean }>,
): Promise<void> {
  const { reportType } = job.data;
  logger.info({ reportType, jobId: job.id }, 'Auto-generating scheduled report');

  // Find system user
  const systemUser = await prisma.user.findFirst({
    where: { role: 'SUPER_ADMIN', isActive: true },
  });
  if (!systemUser) {
    logger.warn('No SUPER_ADMIN found for scheduled report generation');
    return;
  }

  const now = new Date();
  const periodStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const periodEnd = new Date(now.getFullYear(), now.getMonth(), 0);

  // Create report record
  await prisma.regulatoryReport.create({
    data: {
      reportType: reportType as never,
      status: 'GENERATING',
      periodStart,
      periodEnd,
      generatedBy: systemUser.id,
    },
  });

  logger.info({ reportType }, 'Scheduled report enqueued');
}
